name: Run Node.js Script

on: [push]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # Map your secrets to environment variables here
      - name: Run Application
        run: node index.js
        env:
          DATABASE_URL: ${{ secrets.name: Run Node.js Script

on: [push]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # Map your secrets to environment variables here
      - name: Run Application
        run: node index.js
        env:
          DATABASE_URL: ${{ secrets.DB_CONNECTION_STRING }}
